# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cead83adb0c0b34833865bd939722690fc0083c0670a9c5d6209a427e0068f4bb58d0a0dcc8637af04f1ce3df9594f7dc425c92733415eaba55b28b8bf6e1629

test:
  secret_key_base: 54b536e65c240742cc690e405c25d67e4906dd20c25684da399220198aefaa90aaf4ae2a6c4c3f02ab7bd60c25ebbd7408388cb9e4c6c11ff2d86306e815148c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
